NAME=auth
DESCRIPTION="Authentication"

INSTALL=/usr/bin/install

all: 
clean: 
install: install-backend install-po install-ui

include /usr/share/alterator/build/po.mak
include /usr/share/alterator/build/ui2.mak
include /usr/share/alterator/build/backend.mak

